apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hazel-embedded-deployment
  labels:
    app: springboot-hazel-embedded
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-hazel-embedded
  template:
    metadata:
      labels:
        app: springboot-hazel-embedded
    spec:
      containers:
      - name: k8-springboot-hazel
        image: k8-springboot-hazel
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-hazel-embedded-multicast-svc
  labels:
    app: springboot-hazel-embedded
spec:
  type: ClusterIP
  ports:
  - port: 5701
    protocol: TCP
    name: hazelcast    
  selector:
    app: springboot-hazel-embedded
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-hazel-embedded-http-svc
  labels:
    app: springboot-hazel-embedded
spec:
  type: NodePort
  ports:
  - port: 31237
    nodePort: 30126
    targetPort: 8081
    protocol: TCP
    name: http          
  selector:
    app: springboot-hazel-embedded

